### ISSUE TITLE
ERROR: relation "event-store-prod-0.30.1-bxqndo.subscribers" does not exist

### ISSUE THREAD

**Issue by krutilin** [reimagined/resolve-cloud#131]
**Describe the bug**
After the update of the cloud stage to the latest 0.30.1 resolve version, I received the following error on read models list.

![image](https://user-images.githubusercontent.com/5825789/117361315-8dc02380-aec2-11eb-8571-69cf7830c8d8.png)

Note that the event store migrated from 0.29.0 to 0.30.1, here is [a detailed log on CI](https://github.com/DevExpress/brewcomputer/runs/2521268658?check_suite_focus=true#step:7:1)

**Comment by MrCheater** [comment]
Fixed in version 0.31.2
