### ISSUE TITLE
RDS Data API inconsistent behaviour

### ISSUE THREAD

**Issue by IhostVlad** [reimagined/resolve-cloud#133]
RDS Data API faced in inconsistent behaviour, so results of database requests can be mixed within different responses (like described here http://redd.it/i4qcz1/ )
All cloud applications including production can crash in any moment
Since RDS Data API is internal AWS-controlled service, it can't be fixed from resolve-cloud side
Possible solution: migrate to VPC-based adapter ASAP

**Comment by MrCheater** [comment]
Migrate to VPC-based adapter ASAP - Done
