### ISSUE TITLE
Cannot clone event-store with 5kk events (connect timeout after 15 min)

### ISSUE THREAD

**Issue by pavsenin** [reimagined/resolve-cloud#137]
**To Reproduce**
c:\testcafe\testcafe-dashboard>yarn resolve-cloud event-stores clone s2n9cp
yarn run v1.22.4
$ c:\testcafe\testcafe-dashboard\node_modules\.bin\resolve-cloud event-stores clone s2n9cp

 ERROR  Connection timed out after 300000ms                                                                                                                                                                                        17:23:45

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

c:\testcafe\testcafe-dashboard>
- ReSolve Version 0.31.2

**Comment by pavsenin** [comment]
C:\testcafe\testcafe-dashboard>yarn resolve-cloud event-stores clone wd68nt
yarn run v1.22.4
$ C:\testcafe\testcafe-dashboard\node_modules\.bin\resolve-cloud event-stores clone wd68nt

 ERROR  Command has been completed with status "FAILED"                                                                                                                                         10:26:25

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by MrCheater** [comment]
**Additional context:**
Started: Aug 31, 2021 10:11:22.528 AM
End Time: Aug 31, 2021 10:26:23.637 AM
Version: "0.30.2"

**Comment by MrCheater** [comment]
Fixed
