### ISSUE TITLE
Http error:  HttpError: Error: cluster  does not belong to the calling account id on viewModel query.

### ISSUE THREAD

**Issue by krutilin** [reimagined/resolve-cloud#53]
Http error:  HttpError: Error: cluster arn:aws:rds:eu-west-1:169462466426:cluster:event-store-postgres does not belong to the calling account id 650139044964
<img width="754" alt="Screenshot 2020-02-18 at 13 50 50" src="https://user-images.githubusercontent.com/5825789/74729575-b6c0ae00-5255-11ea-8941-3e01257f81fd.png">

Reproducible on the brewcomputer recipe view.

**Comment by alexslavr** [comment]
![Screenshot 2020-02-19 at 11 50 27](https://user-images.githubusercontent.com/36633600/74817661-52155a00-530e-11ea-8e27-2da65b55c277.png)
Same error on command

**Comment by krutilin** [comment]
If you use AWS sdk in your application. And modify AWS.config, you could easily ruin AWS lambda credentials where your app lives. Use 
https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/prog-services-sts.html 
or 
new AWS.Config({...}) without modifying root config.
