### ISSUE TITLE
Duplicated error in UI.

### ISSUE THREAD

**Issue by krutilin** [reimagined/resolve-cloud#66]
<img width="925" alt="Screenshot 2020-05-13 16 21 36" src="https://user-images.githubusercontent.com/5825789/81817899-fdacff80-9535-11ea-9d84-0a11a129dcb2.png">
Try to add a domain with an existing name. Receive two error messages with the same content.

**Comment by sokolov11** [comment]
@krutilin Thank you for your feedback. After reproducing it our team will see what can be done regarding your report.
