### ISSUE TITLE
Can't bind root domain name.

### ISSUE THREAD

**Issue by krutilin** [reimagined/resolve-cloud#68]
<img width="1262" alt="Screenshot 2020-05-13 16 36 11" src="https://user-images.githubusercontent.com/5825789/81819372-e8d16b80-9537-11ea-8ca5-f532e4c1adba.png">
Why domain name "brewcomputer.com" is invalid according to the error?. It looks like a fully qualified second-level domain name like root-domain.org.

same issue with
<img width="1262" alt="Screenshot 2020-05-13 16 41 06" src="https://user-images.githubusercontent.com/5825789/81819909-9775ac00-9538-11ea-8fb8-28962688e2c1.png">

**Comment by max-vasin** [comment]
Currently, where is no support for A domain records. You can only bind thrid-level domains, such as 'www'. We'll fix the error message.

**Comment by krutilin** [comment]
Great, because message is a bit confusing.

**Comment by MrCheater** [comment]
Fixed in version 0.28.2
