### ISSUE TITLE
Cloud-deploy command should have an option to return only the deployed app Id

### ISSUE THREAD

**Issue by SergeyShurygin** [reimagined/resolve-cloud#71]
This will allow not to parse human-readable text in  automatic deplying scripts

**Comment by SergeyShurygin** [comment]
The --filter& -q params for the list command (as they works in docker ps) would be nice too

**Comment by MrCheater** [comment]
`resolve-cloud deploy --format={{ deploymentId }}`
Fixed in version 0.28.2
