### ISSUE TITLE
ERROR 403: Cannot get file via URL provided by the uploader module

### ISSUE THREAD

**Issue by aleks-pro** [reimagined/resolve-cloud#83]
Steps to reproduce:
1. You should have a deployment with uploads in previous resolve version
2. Migrate the deployment events to new resolve cloud version
3. Try to get uploaded file via url provided by uploader
You should get the following response:
```xml
<Error>
    <Code>
        AccessDenied
    </Code>
    <Message>
        Access Denied
    </Message>
    <RequestId>
        DB0350E77E52DC13
    </RequestId>
    <HostId>
        COlpfsBueaFM/zuvtf4NnHItqZdrKRAIbjlIeZ2DQwAUmB5SZtt8WviKbmN/mEpWAAkDnhXJZQc=
    </HostId>
</Error>
```

**Comment by timbset** [comment]
It is fixed by migrating of file storage
