### ISSUE TITLE
ERROR  500: Lambda was unable to decrypt the environment variables...

### ISSUE THREAD

**Issue by alexslavr** [reimagined/resolve-cloud#84]
Resolve-cloud deploy failed with error:
ERROR  500: Lambda was unable to decrypt the environment variables because KMS access was denied. Please check the function's KMS key settings. KMS Exception: UnrecognizedClientExceptionKMS Message: The security token included in the request is invalid.

**Comment by MrCheater** [comment]
Fixed in version 0.28.2
