### ISSUE TITLE
Broken resolve-cloud read-models output

### ISSUE THREAD

**Issue by Skudnoff** [reimagined/resolve-cloud#91]
`resolve-cloud read-models` command may return broken data.

I have 3 read-models `A`, `B` and `C`. `B` is broken and has a big `LAST ERROR` message.
When I call `resolve-cloud read-midels <deployment id>` I get a response. This response contains rows for `A` and `B`. `C` is absent.

Platform: WSL Debian 9.
Resolve-cloud version: 0.14

**Comment by MrCheater** [comment]
Fixed in version 0.28.2
