### ISSUE TITLE
Unable to deploy resolve app to a cloud

### ISSUE THREAD

**Issue by aleks-pro** [reimagined/resolve-cloud#99]
The following errors appear run `yarn resolve-cloud deploy` command:
- `[error] unexpected deployment status "error" with error: "Error: 2020-09-07T09:14:18.846Z 74ae7c4a-8a92-4e5b-a69a-7a85182f0ebe Task timed out after 30.03 seconds at "arn:aws:lambda:eu-west-1:169462466426:function:pool-lambda-prod"`
- `[error] 500: 2020-09-05T18:18:39.165Z b8f3d10a-2162-417f-bce0-b7362831b825 Task timed out after 30.03 seconds`

**Comment by Lykoi18** [comment]
Fixed in version 0.16.0
